### ISSUE TITLE
Error gridsearch assigment 3 question 3.2

### ISSUE THREAD

**Issue by VeronicaAerden** [TPM34A/Q2_2022#7]
In assignment 3.2 where the question is Tune the hyperparameters of your MLP. The gridsearch  (mlp_gridsearch.fit(X_train, Y_train)) gives a lot of errors 'NotFittedError: All estimators failed to fit'. Do you know what the problem could be?
For the full error message see below.

/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: 
135 fits failed out of a total of 135.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
27 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py", line 393, in _fit
    X, y = self._validate_input(X, y, incremental, reset=first_pass)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py", line 1131, in _validate_input
    self._label_binarizer.fit(y)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/preprocessing/_label.py", line 301, in fit
    self.classes_ = unique_labels(y)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/utils/multiclass.py", line 101, in unique_labels
    raise ValueError("Unknown label type: %s" % repr(ys))
ValueError: Unknown label type: (array([0.39130435, 0.5483871 , 0.48888889, ..., 0.52941176, 0.26315789,
       0.44680851]),)

--------------------------------------------------------------------------------
81 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py", line 393, in _fit
    X, y = self._validate_input(X, y, incremental, reset=first_pass)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py", line 1131, in _validate_input
    self._label_binarizer.fit(y)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/preprocessing/_label.py", line 301, in fit
    self.classes_ = unique_labels(y)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/utils/multiclass.py", line 101, in unique_labels
    raise ValueError("Unknown label type: %s" % repr(ys))
ValueError: Unknown label type: (array([0.2       , 0.5483871 , 0.63043478, ..., 0.52941176, 0.26315789,
       0.44680851]),)

--------------------------------------------------------------------------------
27 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py", line 393, in _fit
    X, y = self._validate_input(X, y, incremental, reset=first_pass)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py", line 1131, in _validate_input
    self._label_binarizer.fit(y)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/preprocessing/_label.py", line 301, in fit
    self.classes_ = unique_labels(y)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/utils/multiclass.py", line 101, in unique_labels
    raise ValueError("Unknown label type: %s" % repr(ys))
ValueError: Unknown label type: (array([0.2       , 0.5483871 , 0.63043478, ..., 0.61111111, 0.46428571,
       1.        ]),)

  warnings.warn(some_fits_failed_message, FitFailedWarning)
---------------------------------------------------------------------------
NotFittedError                            Traceback (most recent call last)
[<ipython-input-18-c43d1101df2b>](https://localhost:8080/#) in <module>
      1 # Execute the training/gridsearch
----> 2 mlp_gridsearch.fit(X_train, Y_train)

3 frames
[/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py](https://localhost:8080/#) in _insert_error_scores(results, error_score)
    329 
    330     if successful_score is None:
--> 331         raise NotFittedError("All estimators failed to fit")
    332 
    333     if isinstance(successful_score, dict):

NotFittedError: All estimators failed to fit

**Comment by spierenbu** [comment]
Hello Veronica,
This may be due to your python set-up. I can see that you are using python 3.8, which is different from the one in Collab. Are you running this on your own machine?
If so, my first recommendation would be to go for colab. 
Otherwise, you can install everything on your machine but you need to ensure that you have the correct version of python, and of the libraries (using pyenv for installing the correct version of python for instance, and then installing the libraries from the requirements file using pip). This is a bit advanced, and we cannot provide sufficient support (We recommend colab mainly for this reason).
Let me know if the issue persists on Colab.

**Comment by VeronicaAerden** [comment]
Thanks for the quick response. I am already using google colab. Do you know what else it could be?

**Comment by spierenbu** [comment]
Let's see! Could you send the cell where you define mlp_gridsearch?

**Comment by spierenbu** [comment]
The problem comes from the model you are training. You are training a classifier (predicting categories), while you should be training a regressor (predicting a variable). 
- Use MLPRegressor
- Change the scoring function, use mean_squared_error instead of log_loss: make_scorer(mean_squared_error, greater_is_better = False, needs_proba = True)

**Comment by VeronicaAerden** [comment]
Thanks a lot!

**Comment by VeronicaAerden** [comment]
For the people who are still struggling with this problem, remove the needs_probla argument of your scoring function so:

Use MLPRegressor
Change the scoring function, use mean_squared_error instead of log_loss: make_scorer(mean_squared_error, greater_is_better = False)

**Comment by luisadelavega** [comment]
Hi, I changed the MLP according to the parameters indicated here, which solved the issue. However when I fit the model 
mlp_gridsearch.fit(X_train, Y_train), I receive a new error:
"UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan]
  warnings.warn("

I've checked the Tests and there are no infinite or nan values. Do you know what is causing that?



That's my code:


# Create MLP object (plain vanilla MLP)
mlp_gs = MLPRegressor(activation = 'tanh', solver='adam', batch_size=250, max_iter=2000)

# Define the hyperparameter search space
# 'hidden_layer_sizes' defines the number of nodes and layers
# 'alpha' governs the L2 regularisation
# 'learning_rate_init' governs the learning rate.
hyperparameter_space = {
    'hidden_layer_sizes': [(20,20),(30,30),(25,25)],
    'alpha': [5,1,0.1],
    'learning_rate_init': [0.01,0.001,0.0001]}

# Create scoring function
mean_square = make_scorer(mean_squared_error, greater_is_better = False, needs_proba = True)

# Create the grid_search object, with using the MLP classifier
folds = 5 # Number of cross validation splits
mlp_gridsearch = GridSearchCV(mlp_gs, hyperparameter_space, n_jobs=-1, cv=folds,scoring = mean_square)
mlp_gridsearch.fit(X_train, Y_train)


Thank you!

**Comment by Anne-Kee** [comment]
@luisadelavega As explained in the comment above yours, take away needs_proba = True and run your complete code again. That fixed the same problem for Veronica and me

**Comment by luisadelavega** [comment]
Oh that's true, I didn't notice that. Now it works, thank you very much both of you :)
